global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'worker'
    static_configs:
      - targets: ['worker:8001']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
